server:
  port: 9072

spring:
 thymeleaf:
  cache: false

hibernate.ddl.mode: create

db:
 provider: mysql
 h2:
  dialect: org.hibernate.dialect.H2Dialect
  driver: org.h2.Driver
  url: jdbc:h2:mem:datajpa
  user: sa
  pass: 
 mysql:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/edcircle
  user: root
  password: mysql
  
logging.level:
 org.thymeleaf: INFO
 org.springframework.security: INFO
 org.springframework.jdbc: INFO
 com.edcircle: DEBUG